name: Publish Docker images

on:
  push:
    branches:
     - master

jobs:

  build_all:
    
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image_dir: [circleci-python-java8]
        # assumption: `image_dir` must exactly match Docker Hub repo name and subdir name in this repo

    steps:
    - name: Code checkout
      uses: actions/checkout@master
    - name: Publish ${{ matrix.image_dir }} to docker hub
      uses: elgohr/Publish-Docker-Github-Action@master
        # https://github.com/marketplace/actions/publish-docker
      with:
        name: mattjwnet/${{ matrix.image_dir }}
        workdir: ${{ matrix.image_dir }}
        tags: py3.6.8
        registry: registry.hub.docker.com
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        # For handling secrets in Github Actions, see
        # https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets
        # Use dockerhub Access Tokens rather than passwords:
        # https://hub.docker.com/settings/security
